RNBranch/RNBranch.m, android/src/main/java/io/branch/rnbranch/RNBranchModule.java
This PR allows you to pass `controlParams` (such as `$desktop_url` and `$ios_url`) along with your other link properties to the `showShareSheet` method like so: 
```javascript
const linkProperties = {
feature: 'share',
channel: 'channel',
controlParams: {
'$desktop_url': myContent.desktopShareUrl
}
};
branch.showShareSheet(shareOptions, branchUniversalObject, linkProperties, ({channel, completed, error}) => {});
```
=> Support for controlParams in link properties

RNBranch/RNBranch.m
Allow the share sheet to be shown from a modally presented view controller. Could be changed to use a while loop if we wish to keep moving up the presentation hierarchy until we have the last one but this is a quick fix for many use cases.
=> Allow the share sheet to be shown from presented VC's

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
Fixes crash on app start on Android.
=> - Get Instance from reactActivity.getApplicationContext().

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
My setup (at the moment) has me not extending from `ReactActivity` but `Activity` (and implementing all the gunk in there myself; don't ask, it's all in the quest for a fluid splash screen -- react native 0.29 makes what I'm doing unnecessary which is good).
=> Use base Activity instead of ReactActivity

ios/RNBranch.m
just a lil' typo that resulted in `linkProperties` being null.
=> fix iOS showShareSheet() linkProperties param being null

ios/RNBranch.m
=> Fixes null linkProperties in iOS generateShortUrl()

ios/RNBranch.h
This change along with #22, fixes #20
Issue #22 solves the case, when you integrate existing project with react-native, and want to use CocoaPods for react-native-branch for iOS.
The error about non-modular headers is still there, when trying to use the code from Swift files.
There's a blog post, which explains non-modular headers issue in cocoapods, under the section "Common Header Pitfalls": http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
This problem doesn't appear with Objective C, but does happen in Swift, because swift has a different treatment of modules as well as header files. So when an existing project in Swift gets integrated with react-native and react-native-branch, using cocoapods, the problem above prevents the Swift code from accessing 
RNBranch code, …
=> Fix for issue #20

README.md, ios/RNBranch.m
@rt2zz This was [requested on the core library](https://github.com/BranchMetrics/ios-branch-deep-linking/issues/383) and I had forgotten we already do expose it. This makes the interface a bit more consistent
=> expose email subject for share sheet

README.md
in both the Java and the Objective C, the key is "metadata" not "contentMetadata".
=> fix documentation misprint

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
no longer needed per https://github.com/BranchMetrics/android-branch-deep-linking/blob/7e7dadb2c26bf57a1b7af84925d34e52b50561ab/ChangeLog.md
=> [android] remove deprecated closeSession

docs/setup.md, ios/RNBranch.h, ios/RNBranch.m, testbed/ios/testbed/AppDelegate.m
The purpose of this PR is to allow users to switch from live to test programatically. For this to work, `branch_key` needs to be a dict with both `live` and `test` keys set.
This would be typically used with a compile-time environment switch of some sort:
```objc
if ([env isEqualToString:@"DEV"]) {
[RNBranch useTestInstance];
}
[RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```
=> Adding environment switch for iOS (to use the test key instead of the live one)

README.md, ios/RNBranch.xcodeproj/project.pbxproj
Thanks for this framework!
This PR adds support to be able to install the framework via the [Carthage](https://github.com/Carthage/Carthage) dependency manager.
Essentially, it's just adding the `Carthage` build directory to the target's Framework Search Paths, and adding the framework's `Headers` directory to the target's Header Search Paths. Neither of these changes should have any affect on existing and future CocoaPods integrations, just as including the `Pods` directories in Framework/Header search paths has no affect on Carthage integrations.
I have tested this fork on a private project, and it installs and builds just fine, but feel free to do your own testing.
=> Add support for installation via Carthage

testbed/README.md, testbed/testbed_cocoapods/ios/testbed_cocoapods.xcodeproj/project.pbxproj
This change eliminates the runtime error from testbed_cocoapods by restoring the React libraries to the project (even though React is also in the Podfile). This may not be the last word.
=> Fix testbed_cocoapods

src/index.js
Added a 5 s TTL for the cache. Any callback to a `subscribe` call made at initialization will receive a link that launched the app. Subsequent calls to subscribe, after the TTL has expired, will not receive a cached link. This should address #73. This will be part of the 0.9.1 release.
It would be nice to make the TTL configurable, which was the intention in the first commit, but the `setTimeout()` call in the constructor happens before a caller can set the property value. This can be done without a timeout or using other means. For now, INIT_SESSION_TTL is a constant. The idea was not to encourage users to configure it but to provide a workaround in case the default value doesn't work in some situation. This can still be added one way or another.
=> Subscribe cache TTL (0.9.1)

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m
Added support for the following link properties to address #84:
- alias
- campaign
- stage
- tags
e.g.:
```js
let linkProperties = { feature: 'share', channel: 'RNApp', alias: 'get', campaign: 'launch', stage: 'level 1', tags: [ 'tag_1', 'tag_2' ] }
```
=> Additional link properties (0.9)

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/BranchLinkProperties+RNBranch.h, ios/BranchLinkProperties+RNBranch.m, ios/BranchUniversalObject+RNBranch.h, ios/BranchUniversalObject+RNBranch.m, ios/NSObject+RNBranch.h, ios/NSObject+RNBranch.m, ios/RNBranch.m, ios/RNBranch.xcodeproj/project.pbxproj, ios/RNBranchProperty.h, ios/RNBranchProperty.m
This change is intended to help out in cases like #84. RN users are not necessarily familiar with CocoaPods or Carthage. It's easy to run `pod install`, e.g., get an old version of the SDK and have build problems for reasons that are not obvious (though in that case we can help out in the docs by recommending `pod install --repo-update`). It's also easy to forget to update the native SDK when updating the react-native-branch module. In the long run, I'd like to bundle the Branch SDK in with the native RNBranch code in order to avoid a) the necessity to even install CocoaPods or Carthage in order to use react-native-branch; b) the need to document different installation options; c) any possibility of a version mismatch. This closely resembles the way that Facebook bundles all native code …
=> Portability 0.9 (iOS)

ios/RNBranch.xcodeproj/project.pbxproj
The library will currently prevent you submitting your app to the App Store because it includes a public header. Because of this, Xcode will think the generated archive is "generic" and will not allow you to upload it to iTunes Connect.
This PR fixes this by making all headers "project headers".
See here for more information:
* http://stackoverflow.com/a/13620628/99582
* https://developer.apple.com/library/content/technotes/tn2215/_index.html#//apple_ref/doc/uid/DTS40011221-CH1-HD1
=> Ensure all headers are project to allow iOS archiving

README.md
Missing closing parenthesis added to `branchUniversalObject` variable declaration in README Usage section.
=> Correct syntax error in README

docs/setup.md, testbed/testbed_carthage/android/app/src/main/java/com/testbed_carthage/MainActivity.java
Follow up on commit 779a5f3c34a3c2192b2cbe7c00b93973b9e6da87. There were comments referencing the no longer used `onStop` function.
=> [android] Remove onStop remains from the docs

ios/RNBranch.m, package.json
Allow users of react-native-branch to receive `branch.subscribe` callbacks for non-Branch Universal and App Links. See #102.
For some reason, the callbacks to initSession in each native layer filter out params that do not contain the `~id` parameter. The JS callback is invoked, but params is null. Since only Branch links have that parameter, non-Branch opens return null for params, and the `+non_branch_link` parameter is not available.
The Android native layer passes the original URL in the `uri` property of the object passed to the `branch.subscribe` callback in every case. The iOS native layer was only doing this for custom URIs, not Universal Links. That is the only change in this PR: Pass the `uri` parameter for iOS Universal Links as well, for consistency. Now that field will always …
=> Non-Branch URLs

testbed/testbed_carthage/android/app/app.iml, testbed/testbed_carthage/android/app/src/main/java/com/testbed_carthage/MainApplication.java, testbed/testbed_carthage/index.android.js, testbed/testbed_carthage/index.ios.js, testbed/testbed_carthage/package.json, testbed/testbed_carthage/src/Subscribe.js, testbed/testbed_carthage/yarn.lock, testbed/testbed_cocoapods/android/app/app.iml, testbed/testbed_cocoapods/android/app/src/main/AndroidManifest.xml, testbed/testbed_cocoapods/android/app/src/main/java/com/testbed_cocoapods/MainApplication.java, testbed/testbed_cocoapods/index.android.js, testbed/testbed_cocoapods/index.ios.js, testbed/testbed_cocoapods/package.json, testbed/testbed_cocoapods/src/Subscribe.js, testbed/testbed_cocoapods/yarn.lock
Added a simple example of using `branch.subscribe` to the testbed apps. This is also useful for testing. It just dumps out the data received in the callback.
Also updated dependencies, particularly to RN 0.41.2.
=> Subscribe in testbed

ios/RNBranch.xcodeproj/project.pbxproj
See #106.
This adds a recursive framework search path at the project level for a manually-installed Branch SDK. The recursive path is `$(SRCROOT)/../../../ios/**`. This will search the RN project's ios subdirectory and all its subdirectories recursively.
=> Add a recursive framework search path for manual installation

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, src/branchUniversalObject.js, testbed/testbed_carthage/src/BranchMethods.js, testbed/testbed_cocoapods/android/app/app.iml, testbed/testbed_cocoapods/src/BranchMethods.js
This is a significant internal change to the native layers that establishes a one-to-one relationship between the BranchUniversalObject in each native layer (Android and iOS) and the JS object returned by `branch.createBranchUniversalObject`. In current releases, in a simple snippet like this:
```js
let universalObject = branch.createBranchUniversalObject(...)
universalObject.registerView()
universalObject.showShareSheet(...)
```
Each time a method is called on the `universalObject`, a new temporary native instance of BranchUniversalObject is instantiated using the same parameters. The corresponding method is called on that instance, and then the instance is discarded. This is not in line with Branch's recommended best practices. It is mainly inefficient, but there may also be unintended …
=> Wrap native BUO

android/src/main/java/io/branch/rnbranch/AgingHash.java, android/src/main/java/io/branch/rnbranch/AgingItem.java, android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, ios/RNBranch.xcodeproj/project.pbxproj, ios/RNBranchAgingDictionary.h, ios/RNBranchAgingDictionary.m, ios/RNBranchAgingItem.h, ios/RNBranchAgingItem.m, src/branchUniversalObject.js, testbed/testbed_cocoapods/android/app/app.iml, testbed/testbed_cocoapods/android/app/build.gradle, testbed/testbed_cocoapods/android/build.gradle, testbed/testbed_cocoapods/android/gradle/wrapper/gradle-wrapper.properties, testbed/testbed_cocoapods/android/testbed_cocoapods.iml, testbed/testbed_cocoapods/src/BranchMethods.js
This is a remedy to the growth issue discussed in a [recent pull request](https://github.com/BranchMetrics/react-native-branch-deep-linking/pull/117).
Introduced io.branch.rnbranch.AgingHash (Android) and RNBranchAgingDictionary (iOS). These containers require a TTL at initialization and will purge old entries on insertion. Items that have not been accessed within the TTL are removed from the container whenever a new item is inserted. This prevents long-term, unlimited memory growth.
The original problem is that the native layers never know if the corresponding JS object still exists, so it's possible to make a call after an expired Branch Universal Object has been removed from the native cache, if the JS object is still around. Then the specified ident is not found in the cache, and an …
=> Age cached BUOs

README.md, android/build.gradle, android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, testbed/testbed_carthage/android/app/app.iml, testbed/testbed_carthage/android/app/build.gradle, testbed/testbed_cocoapods/android/app/app.iml, testbed/testbed_cocoapods/android/app/build.gradle
Updated the `com.facebook.react:react-native' requirement in build.gradle to use whatever is in node_modules, rather than pinning to an old version, following the example in the app's build.gradle (generated by RN). AndroidStudio also updated the buildToolsVersion.
Changed the error message generated by the native layers when a BUO is not found, since this always caught in the JS and retried. Also removed some outdated comments.
=> Gradle updates and misc.

ios/BranchUniversalObject+RNBranch.m, package.json
The BranchConstants.h header was only exposed by CocoaPods. Other means of installation would not build (including testbed_carthage). See #128.
=> Carthage fix

ios/RNBranch.h, ios/RNBranch.m, testbed/testbed_native_ios/src/BranchMethods.js, testbed/testbed_native_ios/testbed_native_ios.xcodeproj/project.pbxproj, testbed/testbed_native_ios/testbed_native_ios.xcodeproj/xcshareddata/xcschemes/testbed_native_ios.xcscheme, testbed/testbed_native_ios/testbed_native_ios/AppDelegate.m, testbed/testbed_native_ios/testbed_native_ios/Info.plist, testbed/testbed_native_ios/testbed_native_ios/ViewController.m, testbed/testbed_native_ios/testbed_native_ios/testbed_native_ios.entitlements, testbed/testbed_simple/src/BranchMethods.js
Added `RNBranchLinkOpenedNotification`, generated each time the callback to `[Branch initSessionWithLaunchOptions:isReferrable:andRegisterDeepLinkHandler:]` is invoked. In particular, this allows a native app using the Branch iOS SDK to include a RN component with the react-native-branch module and still route links in the native code and also get callbacks in `branch.subscribe` in the JS app. This is illustrated in changes to the testbed_native_ios app.
=> [OS-19][OS-24] Add native notification for iOS and finish testbed_native_ios

testbed/README.md, testbed/testbed_carthage/README.md, testbed/testbed_carthage/package.json, testbed/testbed_carthage/yarn.lock, testbed/testbed_cocoapods/README.md, testbed/testbed_cocoapods/package.json, testbed/testbed_cocoapods/yarn.lock, testbed/testbed_native_ios/README.md, testbed/testbed_simple/README.md
Keep the old testbed apps, but pin to `react-native-branch@^1.1.1` rather than using the repo contents. Update testbed docs.
=> Update old testbeds

examples/webview_example/src/Article.js
Unlike the native SDKs, react-native-branch defaults contentIndexingMode to private. Spotlight indexing doesn't work unless it's public.
=> Set contentIndexingMode to public in webview_example

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, src/index.js
- Removed all JS caching and subscription management, including _listeners.
- Stop resetting cache in redeemInitSessionResult.
- Use nativeEventEmitter.addListener, .removeListener directly with subscribe listener callback.
=> Cache rework (#79)

examples/webview_example_native_ios/WebViewExample/RCTLog.swift, examples/webview_example_native_ios/WebViewExample/RCTSwiftLog.h, examples/webview_example_native_ios/WebViewExample/RCTSwiftLog.m
Under at least some conditions, I have been unable to generate output from NSLog in the RNBranch module. Hence that module uses the RCTLog macros from <React/RCTLog.h>. The React logger is nicer than NSLog anyway, since it provides log levels with runtime filtering, file and line context and an identifier for the thread that logged the message.
This wrapper lets you use functions with the same name in Swift. For example:
```Swift
RCTLogInfo("application launched")
```
generates
```
2017-04-06 12:31:09.611 [info][tid:main][AppDelegate.swift:18] application launched
```
This is currently part of this sample app. There may be some issues integrating it into an Objective-C library, either react-native-branch or react-native itself, but it may find its way into one or the other eventually. …
=> Improved Swift wrapper around RCTLog and friends.

examples/webview_example/src/Article.js, examples/webview_example_native_ios/src/Article.js
This has come up a few times recently and is useful to address a couple of different issues. It's nice to have an example.
=> Added an $ios_deepview control param to webview_examples

examples/testbed_carthage/src/Subscribe.js, examples/testbed_cocoapods/src/Subscribe.js, examples/testbed_simple/src/Subscribe.js, examples/webview_example/ios/webview_example.xcodeproj/project.pbxproj, examples/webview_example/ios/webview_example/webview_example.entitlements, examples/webview_example/src/App.js
Improve the way the subscribe callbacks are called in the example apps to reflect a recent change in the docs. This is basically a stylistic change that is more natural for JS devs, lines up with the way we call other methods and simplifies the app code. There is no change to the SDK or functional change to the example apps.
=> Destructure subscribe

examples/testbed_native_android/android/app/src/debug/AndroidManifest.xml, examples/testbed_native_android/android/app/src/main/AndroidManifest.xml, examples/testbed_native_ios/testbed_native_ios/AppDelegate.m, examples/testbed_native_ios/testbed_native_ios/Info.plist, examples/testbed_native_ios/testbed_native_ios/testbed_native_ios.entitlements, examples/testbed_simple/android/app/src/debug/AndroidManifest.xml, examples/testbed_simple/android/app/src/main/AndroidManifest.xml, examples/testbed_simple/ios/testbed_simple/AppDelegate.m, examples/testbed_simple/ios/testbed_simple/Info.plist, examples/testbed_simple/ios/testbed_simple/testbed_simple.entitlements, examples/webview_example/android/app/src/debug/AndroidManifest.xml, examples/webview_example/android/app/src/main/AndroidManifest.xml, examples/webview_example/ios/webview_example/AppDelegate.m, examples/webview_example/ios/webview_example/Info.plist, examples/webview_example/ios/webview_example/webview_example.entitlements, examples/webview_example_native_ios/WebViewExample/AppDelegate.swift, examples/webview_example_native_ios/WebViewExample/Info.plist, examples/webview_example_native_ios/WebViewExample/WebViewExample.entitlements
Added Branch test keys to all 2.0.0 examples. All apps, Android and iOS, will use the test instance in debug builds and the live one in release builds for illustration.
=> Branch test keys

examples/webview_example_native_ios/WebViewExample.xcodeproj/project.pbxproj, examples/webview_example_native_ios/WebViewExample.xcodeproj/xcshareddata/xcschemes/WebViewExample-Test.xcscheme, examples/webview_example_native_ios/WebViewExample/AppDelegate.swift
This provides an example of using custom Xcode build configurations with CocoaPods to control which Branch key to use. This approach will only work when using the React pod, because CocoaPods provides the automation to support the custom configurations in the dependencies. This is relevant to #159 and #104.
There is now a WebViewExample-Test scheme that uses the Branch test key in both Debug and Release builds. The WebViewExample scheme uses the live key.
=> iOS custom configuration example

.travis.yml, Gemfile, Gemfile.lock
Use Ruby 2.4.0. 2.3.4 and 2.4.1 are both too recent to have precompiled binaries via RVM, so they add 6-7 minutes to the build time.
Removed ruby declaration from Gemfile, which is confusing and inconvenient.
=> Travis improvements

runAllTests
This was indicated in the contribution instructions but omitted accidentally.
=> Add npm test to runAllTests

.travis.yml, CONTRIBUTING.md, package.json, runAllTests, src/branchUniversalObject.js, src/index.js, test/index.js
The contribution instructions say all contributions must pass eslint. There is now a lint script in package.json. This was added to CI (.travis.yml) and the runAllTests script. The contribution instructions were updated to use `npm run lint`.
A number of eslint violations were also fixed.
=> Added eslint to .travis.yml and runAllTests

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.h, ios/RNBranch.m, ios/RNBranchEventEmitter.h, ios/RNBranchEventEmitter.m, native-tests/ios/NativeTests.xcodeproj/project.pbxproj, native-tests/ios/NativeTestsTests/BranchLinkPropertiesExtensionTests.m, native-tests/ios/NativeTestsTests/RNBranchTests.m, src/index.js, test/helpers/RNBranch.mock.js, test/index.js
Eliminate constants in JS that duplicate constants in the native SDKs in favor of exported constants for better consistency. Added missing AddToCartEvent. Added unit tests in JS and Obj-C for these mappings. Android tests of the RNBranchModule require testing in an emulator, which still remains to be set up.
=> Event constants

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
When there is no initListener, there is no WeakReference.
=> Fix #187: Check WeakReference before calling get()

native-tests/ios/NativeTestsTests/BranchLinkPropertiesExtensionTests.m, native-tests/ios/NativeTestsTests/BranchUniversalObjectExtensionTests.m, native-tests/ios/NativeTestsTests/NSObjectExtensionTests.m, native-tests/ios/NativeTestsTests/RNBranchAgingDictionaryTests.m, native-tests/ios/NativeTestsTests/RNBranchAgingItemTests.m, native-tests/ios/NativeTestsTests/RNBranchTests.m
Use XCTAssertEqualObjects when semantically appropriate rather than XCTAssertEqual.
=> Improvements to iOS unit tests

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, examples/testbed_native_android/src/Subscribe.js, examples/testbed_native_ios/src/Subscribe.js, examples/testbed_simple/src/Subscribe.js, examples/webview_example/src/App.js, ios/RNBranch.m
To conform with the rest of the Branch SDKs, particularly the underlying iOS and Android SDKs, the data model has been changed slightly.
This SDK alone adds a `uri` property in the `subscribe` callback. This was always the original deep link that opened the app, equivalent to the `~referring_link` (Branch) or `+non_branch_link` (non-Branch) parameter returned by the API. However, there was also a filter on the `~id` parameter, a unique identifier assigned to each click on a Branch link. If that was not present, `params` would always be null. In particular, for non-Branch links, there is no `~id` parameter. In that case, the `params` were not passed, and the `+non_branch_link` was unavailable. It was only available via the `uri` field.
This leads to some confusion at times. All unique and …
=> Data model updates

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, docs/setDebug.md, ios/RNBranch.h, ios/RNBranch.m, src/index.js
This method is not supportable without a sizable refactoring because the underlying native call must be made before the native SDK initializes, which happens before the JS loads. It has been indicated in the documentation in the past, however. Simple native calls were added: `[RNBranch setDebug]` (iOS) and `RNBranch.setDebug()` (Android). A document was added with instructions for adding these calls to the native code. Now the JS `setDebug` method throws an exception rather than calling the native layer. The error message includes a link to this doc.
In a future release we may be able to offer the option to delay native SDK initialization until the JS has loaded and support a number of unsupportable features like this.
An overhaul of the documentation is part of the 2.0.0 release and is …
=> Disable setDebug()

README.md
Update docs to reflect deprecation of the `uri` parameter in the `subscribe` callback.
=> Deprecated uri in docs

ios/RNBranch.h, ios/RNBranch.m
Added
- `[RNBranch setRequestMetadataKey:value:]`, particularly for Mixpanel integration.
- `[RNBranch delayInitToCheckForSearchAds]`
- `[RNBranch setAppleSearchAdsDebugMode]`
These are wrappers around the underlying Branch SDK calls, but since the RNBranch object manages its own Branch instance (controlled by `[RNBranch useTestInstance]`), this simplifies matters for native callers. Instead of adding `#import <Branch/Branch.h>` and, e.g.:
```Obj-C
#ifdef DEBUG
[[Branch getTestInstance] delayInitToCheckForSearchAds];
#else
[[Branch getInstance] delayInitToCheckForSearchAds];
#endif
[RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```
Now you can just add:
```Obj-C
[RNBranch delayInitToCheckForSearchAds];
[RNBranch initSessionWithLaunchOptions:launchOptions …
```
=> Added some wrapper methods for iOS

docs/updating-1.0.0.md
Complement docs with breaking changes in the definition of the createBranchUniversalObject function.
=> Add Branch API breaking changes in v1.1.0

examples/testbed_native_ios/testbed_native_ios/AppDelegate.m, examples/testbed_simple/ios/testbed_simple/AppDelegate.m, examples/webview_example/ios/webview_example/AppDelegate.m, examples/webview_example_native_ios/WebViewExample/AppDelegate.swift, ios/RNBranch.h, ios/RNBranch.m
- Introduced `RNBranch.branch` class property to expose the Branch instance used.
- Added a deprecation message to `handleDeepLink:`
- Converted examples to use the newer methods on the Branch instance.
=> Deprecated [RNBranch handleDeepLink:]

android/src/main/java/io/branch/rnbranch/RNBranchConfig.java, android/src/main/java/io/branch/rnbranch/RNBranchModule.java, branch.example.json, docs/branch.json.md, examples/testbed_simple/branch.debug.json, examples/testbed_simple/branch.json, examples/webview_example/branch.debug.json, examples/webview_example/branch.json, examples/webview_example/ios/webview_example.xcodeproj/project.pbxproj, ios/RNBranch.m, ios/RNBranchConfig.h, ios/RNBranchConfig.m, scripts/addBranchConfig.js, scripts/androidUtil.js, scripts/iosUtil.js, scripts/removeBranchConfig.js, test/helpers/RNBranch.mock.js
The `branch.json` file can now be used to control key selection using several new parameters. Support was also added for Apple Search Ads on iOS.
New parameters:
|key|description|type|
|---|---|---|
|branchKey|If set, the specified key overrides all other settings, including the Info.plist, AndroidManifest.xml and the liveKey and testKey settings here.|String|
|liveKey|If branchKey is not set and useTestInstance is false or absent, this key will be used to override the keys from the Info.plist and AndroidManifest.xml|String|
|testKey|If branchKey is not set and useTestInstance is true, this key will be used to override the keys from the Info.plist and AndroidManifest.xml|String|
|useTestInstance|If branchKey is not set and useTestInstance is true, the testKey from branch.json will be used …
=> More settings in branch.json

docs/branch.json.md, ios/RNBranchConfig.m, scripts/addBranchConfig.js, scripts/androidUtil.js, scripts/iosUtil.js
This change introduces support for branch.android.json, branch.ios.json, branch.android.debug.json and branch.ios.debug.json to allow for platform-specific configuration. This primarily affects the react-native link automation.
=> Platform-specific branch.json

android/src/main/java/io/branch/rnbranch/RNBranchPackage.java
[`createJSModules` is now not required on Android](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8) from RN 0.47. I actually can't build an app on RN 0.47 without removing this method. This is backwards compatible according to my tests (in comparison to #228).
=> Remove createJSModules - RN 0.47 compatibility

fastlane/lib/update_native_sdks.rb, ios/RNBranch.xcodeproj/project.pbxproj
When updating the SDK, files can move around and groups can become empty in the RNBranch.xcodeproj. The automation was too aggressively cleaning up empty groups, resulting in an invalid Products group. This change limits the clean-up to the Branch-SDK group. The RNBranch.xcodeproj was regenerated after this change.
Fix #239. This will be released soon, after further testing.
=> Automation fixes

Gemfile.lock, README.md, examples/testbed_native_android/android/app/src/main/AndroidManifest.xml, examples/testbed_native_ios/testbed_native_ios.xcodeproj/project.pbxproj, examples/testbed_simple/android/app/src/main/AndroidManifest.xml, examples/testbed_simple/ios/testbed_simple.xcodeproj/project.pbxproj, examples/webview_example/android/app/src/main/AndroidManifest.xml, examples/webview_example/ios/webview_example.xcodeproj/project.pbxproj, examples/webview_example/package-lock.json, examples/webview_example/package.json, examples/webview_example/src/App.js, examples/webview_example/yarn.lock, examples/webview_example_native_ios/WebViewExample.xcodeproj/project.pbxproj
- Regenerated Android manifests with an updated branch plugin to fix an error (autoverify instead of autoVerify).
- Navigator moved to react-native-deprecated-custom-components. This was causing a crash in webview_example.
- Added CoreSpotlight, AdSupport and SafariServices frameworks to all Xcode projects.
=> More example updates

Gemfile.lock, fastlane/lib/update_native_sdks.rb
Added some options to the `update_native_sdks` action to make it easier to work with tags and branches in the native repos: `:android_checkout`, `:ios_checkout` and `:commit`. For example, to work with the framework-improvements branch in the iOS repo without committing:
```Ruby
update_native_sdks ios_checkout: "framework-improvements", commit: false
```
The `:android_checkout` and `:ios_checkout` keys can take as arguments branches, tags or commits (SHA). The string is just passed to `git checkout`.
=> Automation updates

README.md, android/src/main/java/io/branch/rnbranch/RNBranchModule.java, examples/testbed_native_ios/Podfile.lock, examples/testbed_native_ios/Pods/Local Podspecs/react-native-branch.podspec.json, examples/testbed_native_ios/Pods/Manifest.lock, examples/webview_example/android/app/build.gradle, examples/webview_example/android/app/src/main/java/com/webview_example/MainActivity.java, examples/webview_example_native_ios/Podfile.lock, examples/webview_example_native_ios/Pods/Local Podspecs/react-native-branch.podspec.json, examples/webview_example_native_ios/Pods/Manifest.lock, examples/webview_example_native_ios/Pods/Target Support Files/react-native-branch/Info.plist, ios/RNBranch.m, native-tests/ios/Podfile.lock, native-tests/ios/Pods/Local Podspecs/react-native-branch.podspec.json, native-tests/ios/Pods/Manifest.lock, package.json, src/index.js
Addresses #243.
This change introduces a `branch.openURL` method that can be used to trigger open events from Branch and non-Branch links programmatically from anywhere in the app: a push notification, QR reader, etc.
=> openURL method

README.md, android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, src/index.js
This allows you to specify a bucket for which to load rewards. I saw this was implemented in the Cordova version so I added it here.
Linting and tests pass, and I checked that this works on  both platforms. Let me know if this looks good!
=> Allow loading rewards for different buckets

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m
In case an alias is taken, return a standardized error code to JS.
=> Return RNBranch::Error::DuplicateResourceError from generateShortUrl

examples/browser_example/android/app/build.gradle, examples/browser_example/android/app/src/main/java/com/browser_example/MainApplication.java, examples/testbed_native_android/android/app/build.gradle, examples/testbed_native_android/android/app/src/main/java/io/branch/testbed_native_android/MainApplication.java, examples/testbed_simple/android/app/build.gradle, examples/testbed_simple/android/app/src/main/java/com/testbed_simple/MainApplication.java, examples/webview_example/android/app/src/main/java/com/webview_example/MainApplication.java
Judging from problem reports, a lot of production apps enable multidexing. This has an effect on error messages, etc. Enabling multidexing in all the example Android apps to better match production apps.
This may be related to #256.
=> Enable multidexing in all Android examples

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
I get the following below session params. Because error is populated as a key (but has value of `null`), the sdk categorizes the initialization as a`RNBranch.initSessionError` event.  This PR fixes that.
```
{
"params": {
"$og_title": "...",
"$publicly_indexable": 0,
"~creation_source": 3,
"$og_description": "...",
"+click_timestamp": 1510001640,
"+from_facebook_ad": true,
"$identity_id": 359755702476408775,
"$og_image_url": "...",
"+match_guaranteed": true,
"$canonical_identifier": "...",
"+clicked_branch_link": true,
"$one_time_use": false,
"~id": 455075964863574517,
"+is_first_session": false,
"~referring_link": "...",
"$exp_date": 0
},
"error": null,
"uri": "..."
}
```
=> Fix incorrect event type when error = null

fastlane/lib/update_native_sdks.rb, ios/RNBranch.xcodeproj/project.pbxproj
The automated SDK update did not completely handle removal of a .pch file. This has been corrected in the automation and the RNBranch.xcodeproj.
=> Automation fix

src/BranchEvent.js, src/branchUniversalObject.js, test/BranchEventTest.js
When a native BUO has expired from the native cache, any attempt to call a method on that BUO will result in `RNBranch::Error::BUONotFound` being raised. When working with a single BUO, this error is caught, a new native BUO is created, and the method is retried. Something similar is now done in `BranchEvent.logEvent()` in case multiple BUOs are attached to the same event. Any expired BUO is recreated and the method retried.
=> Handle expired BUOs in BranchEvent.logEvent()

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/BranchContentMetadata+RNBranch.m, ios/RNBranch.m
Fixes a crash caused by some field-mapping issues when using productCategory on Android or addressPostalCode on iOS.
=> Fix bad field mappings

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, fastlane/Fastfile, fastlane/lib/actions/update_native_sdks.rb, fastlane/lib/actions/version_bump.rb, fastlane/lib/helper/update_helper.rb, ios/RNBranch.m, src/branchUniversalObject.js, src/index.js
Added version reporting in the logs at initialization. The native SDK version and the react-native-branch version are both reported. There is also now a `VERSION` constant in index.js that indicates the current version.
Added a `bump` lane to the Fastfile for automating version bumps, which involves a sequence of yarn and pod update commands to make sure the Pods sandboxes are all updated as well as automatically updating the constant in index.js.
Fixed some other issues involving Android initialization and conversion of the contentMetadata.price field.
=> Automated version bump and bug fixes

ios/RNBranch.m
Probably related to #308.
The current release doesn't build with Xcode 8. Earlier versions of Xcode 9 were extremely pedantic about certain things. An unnecessary check for iOS 8 (RN only supports 8+) had to be introduced to silence a warning. However, this fails to build with Xcode 8, and removing the check no longer produces a warning in Xcode 9.
=> Get rid of unnecessary version check for iOS 8

examples/testbed_native_android/package-lock.json, examples/testbed_native_android/package.json, examples/testbed_native_ios/package-lock.json, examples/testbed_native_ios/package.json, examples/webview_example_native_ios/package-lock.json, examples/webview_example_native_ios/package.json, package-lock.json, package.json
There is a potential security vulnerability with one of our underlying dependencies. Currently, we depend on `react-native 0.43.1`. This PR updates that dependecy to `react-native ^0.43.0` (the latest non-breaking version). By doing this, `moment 2.18.1` updates to `moment 2.22.1` which is greater than the `moment 2.19.3` security fix.
@aaaronlopez can you please test that this PR to confirm nothing breaks?
cc @sojanpr @hubt
=> Dependency update

README.md
Ensures correct code syntax highlighting in code example.
=> Fix interpolated string in README

android/build.gradle, examples/browser_example/android/app/build.gradle, examples/browser_example/android/app/src/main/AndroidManifest.xml, examples/browser_example/android/build.gradle, examples/browser_example/android/gradle/wrapper/gradle-wrapper.properties, examples/testbed_native_android/android/app/build.gradle, examples/testbed_native_android/android/build.gradle, examples/testbed_native_android/android/gradle/wrapper/gradle-wrapper.properties, examples/testbed_simple/android/app/build.gradle, examples/testbed_simple/android/app/src/main/AndroidManifest.xml, examples/testbed_simple/android/build.gradle, examples/testbed_simple/android/gradle/wrapper/gradle-wrapper.properties, examples/webview_example/android/app/build.gradle, examples/webview_example/android/app/src/main/AndroidManifest.xml, examples/webview_example/android/build.gradle, examples/webview_example/android/gradle/wrapper/gradle-wrapper.properties, examples/webview_example/branch.debug.json, examples/webview_example/branch.json, examples/webview_example/src/ArticleList.js, ios/RNBranch.m, src/index.js
Supporting keys from JS requires some significant changes on the Android side. This may even involve modifications to the native Android SDK. I'm reviewing this with the Branch devs, to be resolved soon. Meanwhile, need to do a release.
This temporarily addresses a long-standing Android build issue by taking the Branch SDK from Maven from the time being, rather than from the jar in the repo.
=> Back out key support

src/index.js
Related to issue #363
Fixed issue by adding a check that the `params` property is not `null` or `undefined`
=> Added check for params property to not be null or undefined

examples/webview_example/ios/webview_example/Info.plist
This commit was omitted in #417. This removes the Branch keys from Info.plist in webview_example in order to prove they're taken from branch.json.
=> Remove keys from Info.plist for webview_example

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
The weakref is getting garbage collected when the app is not opened via
a Branch.io link.
Closes #371
=> [Android] remove WeakReference from BranchUniversalReferralInitListener

package.json, react-native-branch-segment.podspec
Addresses #401.
This adds a `react-native-branch-segment` pod that addresses a dependency conflict.
The pods here are only intended for use with hybrid apps: native iOS apps written in Swift or Obj-C that include one or more RN components. If you're using `react-native link` (or `rnpm link`) to build your app, the Branch native iOS SDK is embedded in the `react-native-branch` project.
To use this pod in an app using the Branch Segment integration, add this to your Podfile:
```Ruby
pod "react-native-branch-segment", path: "node_modules/react-native-branch" # or wherever your node_modules is
```
Instead of
```Ruby
pod "react-native-branch", path: "node_modules/react-native-branch"
pod "Branch-SDK", path: "node_modules/react-native-branch/ios"
```
Be sure you're not including the Branch-SDK …
=> Segment fix

ChangeLog.md, README.md
This was omitted and only mentioned in the Release Notes and the ChangeLog (as well as the notes to #426).
Changes to the ChangeLog formatting to match the release notes for better MD formatting.
=> Mention CocoaPods in README installation instructions

README.md, android/build.gradle, examples/browser_example/android/app/build.gradle, examples/testbed_native_android/android/app/build.gradle, examples/testbed_simple/android/app/build.gradle, examples/webview_example/android/app/build.gradle, examples/webview_tutorial/README.md, examples/webview_tutorial/android/app/proguard-rules.pro, examples/webview_tutorial/android/app/src/main/java/com/webview_tutorial/MainActivity.java, examples/webview_tutorial/android/app/src/main/java/com/webview_tutorial/MainApplication.java, native-tests/android/app/build.gradle
This appears at last to be the right solution to the native Android SDK dependency and simplifies matters considerably. The build.gradle for this module now imports the SDK using `api` instead of `implementation`. This exposes the native Branch SDK to native code. This is necessary if you opt to continue using `Branch.getAutoInstance` in `Application.onCreate` instead of `RNBranchModule.getAutoInstance`, which is recommended, since that may be used to support other features in the future, but currently only required if you want to use branch.json to set your keys instead of setting them in the Android manifest.
This also facilitates integrating RN into a native Android app. Exposing the Branch SDK from this module helps prevent conflicts if the native app is also calling the native SDK. …
=> Use api in react-native-branch build.gradle for Branch SDK.

README.md, docs/convert-to-react-pod.md
The README has been updated to reflect the necessity of using the React pod from node_modules. This actually simplifies matters, since there is now only one supported integration path for iOS.
The conversion instructions were updated. The first pod install is not necessary. There is also mention of the `use_frameworks!` option.
=> Update docs for React pod

docs/convert-to-react-pod.md
The instructions now include a test `target` block in the Podfile as well as a more complete list of subspecs for the app target. This is the same as the contents of the Libraries group in a fresh project created with `react-native init`. Including a full list increases the likelihood of building on the first try. Later Partners can remove any subspecs they aren't using to reduce app size.
=> Updated boilerplate Podfile in instructions.

android/build.gradle, ios/RNBranch.xcodeproj/project.pbxproj
Added Carthage/Build/iOS to Framework Search Paths in order to support installing Branch.framework via Carthage.
Bumped native Android SDK to 3.2.0 in preparation for release.
Docs PR to follow momentarily.
=> Carthage support

README.md
When using Objective-C `#import`s with CocoaPods >= 1.7, it is necessary to
`#import <react_native_branch/RNBranch.h>`
The unit tests/CI and some examples are broken as a result of updating. This will be fixed shortly.
=> Update instructions for CocoaPods 1.7

ios/RNBranch.m
Before this change a pointer was being interpreted as a BOOL value, so:
- `nil` would become `false`
- `NSNumber` representing 1 would become `true`
- `NSNumber` representing 0 would also become `true` (a pointer would be non-null)
This change should fix the issue and interpret the value properly.
=> [ios] Fix clicked_branch_link false positive

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m
Fix #465 
This has always worked as designed. There may be no meaningful return value to getLatestReferringParams until the callback to branch.subscribe returns. If the app has previously been opened on the device, the latest referring params will be returned from user defaults (iOS) or user preferences (Android), which may be from a previous run of the app. In that case, the method will return before the callback to subscribe. This is a race:
```js
branch.subscribe(({params, error} => {
// ...
})
let latestParams = await branch.getLatestReferringParams()
```
This is not a race:
```js
branch.subscribe(({params, error} => {
// ...
let latestParams = await branch.getLatestReferringParams()
// of course, latestParams == params, so there's not much case for using the method here
})
```
Both …
=> Use getLatestReferringParamsSync[hronous] in the native layers

README.md, android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, src/index.js
Follow up to #479. Related to #465 
Added an option to getLatestReferringParams to specify synchronous/asynchronous behavior, to avoid breaking any app that relies on the current behavior. By default, the method will remain asynchronous. To wait until an open response is received, use `getLatestReferringParams(true)`.
Also, the remarks for #479 were inaccurate. The synchronous methods will always wait until an open response is received, which is to say when the branch.subscribe callback returns. Only when called asynchronously will the method possibly return data from the user defaults/preferences from a previous app run.
=> Synchronous option for get latest referring params

android/build.gradle, android/src/main/java/io/branch/rnbranch/RNBranchModule.java
Andy added a reInit session method to handle foreground pushes and programmatic linking.  I added the same method to the RNBranch class.  
In the MainActivity onNewIntent, adding RNBranchModule.reInitSession(this) should allow the app to handle programmatic links and foreground pushes.
=> INTENG-6825 android push handling

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, src/index.js
Found its quite important to expose this function to the JS. In the case of Mixpanel integration the distinct ID may change while the app is running and you need to call this again in order to update Branch. Its actually mentioned in your documentation here https://docs.branch.io/integrations/mixpanel/#pass-mixpanel-distinct-id ^_^
=> Expose set request metadata to JS

android/build.gradle
Fix #557 
With this change, I can create a new RN 0.61 app using react-native init, then yarn add this package from local source with these changes and react-native-screens, set up the Android native code, and run without a crash.
If I then revert to react-native-branch@4.4.0, I get the reported runtime error.
=> [SDK-926] Add localbroadcastmanager as a dependency to build.gradle.

ios/RNBranch.m
This change handles Universal Links on iOS at cold launch by looking for the `UIApplicationLaunchOptionsUserActivityDictionaryKey` instead of `UIApplicationLaunchOptionsURLKey`. This is necessary to fire the `onOpenStart` method on cold launch from a Universal Link. That already happens when a UL is opened after launch via contineUserActivity:.
=> [SDK-1035] Handle Universal Links on cold launch (iOS)

native-tests/ios/Podfile.lock, package.json, src/index.js
Fix #590
Returning `subscriber.unsubscribe` from `branch.subscribe` somehow does not result in a working unsubscribe function. Changed to `return () => subscriber.unsubscribe()`, i.e. a function that calls that function. This consistently works in testing.
=> [SDK-1050] Return an appropriate function for unsubscribe.

package.json
This was also done for the Web SDK. The URL takes precedence in some cases (certain NPM commands to report bugs, e.g.).
=> Add bug report email address to package.json

src/BranchSubscriber.js, test/BranchSubscriber.test.js
See comment thread to #530. This adds a parameter `cachedInitialEvent: true` to `onOpenStart` before passing back a cached result. This mirrors the inclusion of `+rn_cached_initial_event` in the `params` to `onOpenComplete`.
=> Cached result in onOpenStart

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, examples/testbed_simple/src/BranchMethods.js, ios/RNBranch.m, src/index.js
Add support for lastAttributedTouchDataWithAttributionWindow. 
This involved adding the method in `RNBranchModule.java` 
```
@ReactMethod
public void lastAttributedTouchDataWithAttributionWindow(int window, final Promise promise) {
Branch branch = Branch.getInstance();
branch.getLastAttributedTouchData(new ServerRequestGetLATD.BranchLastAttributedTouchDataListener() {
@Override
public void onDataFetched(JSONObject jsonObject, BranchError error) {
if (error == null) {
promise.resolve(jsonObject);
} else {
promise.reject(GENERIC_ERROR, error.getMessage());
}
}
}, window);
}
```
As well as adding the method to support iOS builds in RNBranch.m
```
#pragma mark lastAttributedTouchDataWithAttributionWindow
RCT_EXPORT_METHOD(
lastAttributedTouchDataWithAttributionWindow:(NSNumber* …
```
=> Add getLastAttributedTouchData on JS layer in React Native

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
`lastAttributedTouchData` method call on android is currently resolving `JSONObject` instead of `ReadableMap` which leads to a crash.
=> lastAttributedTouchData crash on android

ios/RNBranch.h, ios/RNBranch.m
RNBranch had missing `enableLogging` method, which is per docs, the advised way of debugging as `setDebug` got deprecated.
Currently using it through `patch-package` would be glad if it got merged.
Have a nice day!
=> Add enableLogging to RNBranch

src/index.d.ts
currently if `branch.initSessionTtl` is set typescript will throw an error
=> Add initSessionTtl to branch interface

react-native-branch.podspec
For picking up changes for:
v1.39.3 CORE-1893 Add timeout to Apple attribution token. Some users are reporting the call can hang.
=> Update iOS Branch SDK to v1.39.3

src/index.d.ts
BranchUniversalObject.generateShortUrl returns Promise<{url: string}> not void :)
=> fix BranchUniversalObject.generateShortUrl type

ios/RNBranch.m, react-native-branch.podspec, src/index.d.ts, src/index.js
The react-native-branch library doesn't have the ability to record the ATT Opt-in or Opt-out status. This PR exposes the Branch SDK method `handleATTAuthorizationStatus` to the React Native runtime so that developers using Branch can track the ATT Opt-In event without having to develop native code.
Here is the TypeScript definition of the exposed method. `handleATTAuthorizationStatus` is meant to be called after prompting for the ATT (variety of 3rd party libraries available). The single argument is meant to have a value of either 'authorized', 'denied', 'undetermined', or 'restricted'. Other arguments will have no effect other than logging the error as a console warning.
```
type ATTAuthorizationStatus = 'authorized' | 'denied' | 'undetermined' | 'restricted'
function …
```
=> Expose iOS method handleATTAuthorizationStatus to the React Native JS runtime

src/BranchSubscriber.js
Required fixes for #681.
It is necessary to check against `null` to prevent crashes because sometimes the properties might be null, e.g. because of Fast Refresh or re-rendering.
=> Add checks for listeners remove calls

react-native-branch.podspec
We should depend on React-Core instead of React according to facebook/react-native#29633 (comment). You can check all the related PRs links to this issue.
=> Use React-Core instead of React

ChangeLog.md, android/build.gradle, package.json, react-native-branch.podspec
[SDK-1442] React Native - Patch release 5.4.1 to pick up Branch Android SDK 5.1.5
- Update Android SDK to 5.1.5
- Update iOS SDK to 1.42.0
https://github.com/BranchMetrics/android-branch-deep-linking-attribution/compare/5.1.0...5.1.5
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/compare/1.41.0...1.42.0
[SDK-1442]: https://branch.atlassian.net/browse/SDK-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release 5.4.1

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, SECURITY.md
SDK-1614 -- Github Issue Template for SDK repos
Introduces the new issue report form - references https://github.com/BranchMetrics/web-branch-deep-linking-attribution/issues/new/choose
=> New issue report form

src/index.d.ts
_showShareSheet_ method in BranchUniversalObject has incorrect return type. It indicates that function is sync and returns void. When function is async and returns Promise with a result.
=> Fix BranchUniversalObject showShareSheet return type definition

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, src/index.d.ts, src/index.js
Adds a new method, `setIdentityWithPromise`, which sets the identity/developer_identity and has a promise with returns the first referring params. There already is a `setIdentity` functions which works the same and will still exist. However, it is void/does not return, which is why adding a new method which does.
The native SDKs have two versions of setIdentity, one with a callback and one thats void. This new method uses the one with a callback.
**Existing `setIdentity()`**
```
branch.setIdentity("user123")
```
**New `setIdentityWithPromise()`**
```
let result = branch.setIdentityWithPromise("user456");
result.then((params) => {
console.log('setIdentityWithPromise Result: ', params)
});
```
=> [SDK-1562] Add callback to setIdentity

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, src/index.d.ts
An issue was raised https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/725 wherein calling a `BranchEvent` with `customParams` with non-string values would throw an uncaught exception. 
After review, we decided to define the typing as  
`customData?: Record<string, string>;`
This typing will avoid the mismatch in the native layer.
To test, install the beta containing this change.
https://www.npmjs.com/package/react-native-branch/v/5.6.0-beta.0
via
`npm install — save react-native-branch@beta`
=> [SDK-1517] [ReactNative] customData in track event crash if it's not string

android/src/main/java/io/branch/rnbranch/RNBranchModule.java
SDK-1662 - [Android] error: local variable promise is accessed from within inner class; needs to be declared final
Issue https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/746 was raised noting that there was a compile error when trying to build with the latest package. The solution is to add the `final` modifier over the Promise which gets referenced in an inner class inside `public void setIdentityAsync`. 
This is consistent with the rest of the project's patterns.
Checkout branch and reference locally. You should see no compile errors.
=> Fix setIdentityAsync parameter

ChangeLog.md, package.json
SDK-1665 -- [React Native] Release 5.6.2
- Fixed bug with returning LATD on iOS
- Fixed bug with setIdentityAsync on Android
Integrate and sanity check the release candidate.
=> [SDK-1665] Release 5.6.2

src/index.d.ts
I modified it to be closer to the requirements of the actual js code. All arguments have default values, so it seemed right to give them as optionals.
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/dfa570b073c4fddba189a1604382f0093f514059/src/branchUniversalObject.js#L74
=> Fix BranchUniversalObject#generateShortUrl parameter type definition

src/index.d.ts
Fixes #709
I've tested locally by changing the type manually within `node_modules` folder but you might want to run an e2e or integration test to confirm it doesn't break anything.
=> Change ~creation_source type to be a number

src/index.d.ts
Added export for success and error event to write type guard easily. 
With current implementation we have to either do a force non-null or a null check on `params` regardless of whether you null check error or not.
```ts
branch.subscribe(({error, params}) => {
if (error) {
console.log(error);
} else {
// params could still be undefined here, thus require force non-null, otherwise lint complain
doSomethingWithParams(params);
}
});
```
A better solution is to to write a typeguard like below: 
```ts
function isErrorEvent(
event: BranchSubscriptionEvent,
): event is BranchSubscriptionEventError {
return typeof event.error === 'string';
}
branch.subscribe((event: BranchSubscriptionEvent) => {
if (isErrorEvent(event)) {
console.log(event.error);
} else {
// param cannot be undefined, no …
```
=> Add export to error and success event type

docs/branch.json.md
When installing fresh with RN > 0.60 it is unclear that manual step is required when using branch.json
=> Make it explicit that manual step is required when using branch.json with RN > 0.60

ios/BranchContentMetadata+RNBranch.h, ios/BranchEvent+RNBranch.h, ios/BranchLinkProperties+RNBranch.h, ios/BranchUniversalObject+RNBranch.h, ios/RNBranch.h, ios/RNBranch.m, ios/RNBranchProperty.h, native-tests/ios/NativeTestsTests/RNBranchTests.m, react-native-branch.podspec, src/index.js
SDK-1596
- adds RN code which invokes IOS native method notifyNativeToInit https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/fde54230cd76719d1f57b9d108eb4ca513ccc1c6/BranchSDK/Branch.m#L2164
- updates headers to BranchSDK in place of Branch as per the new Branch IOS sdk 2.1.0
=> [MINOR] Update IOS Branch to BranchSDK 2.1.0

android/build.gradle, branch.example.json, branchreactnativetestbed/package.json, docs/branch.json.md, ios/RNBranch.h, ios/RNBranch.m, react-native-branch.podspec
SDK-1990 -- Bump iOS and Android versions
Bumped the iOS and Android native SDK versions. Also, the latest iOS SDK removed some deprecated Apple Search Ads code, so the respective code was removed here as well.
**iOS: 2.1.0 -> 2.2.0
Android: 5.3.0 -> 5.5.0**
To provide React Native clients access to the latest iOS and Android features.
Try out the latest alpha package (5.9.0-alpha.3) in the testbed app and ensure all functionality is working correctly.
=> [SDK-1990] Update iOS and Android SDK versions

.github/workflows/dependabot-merger.yml
SDK-2032 -- Create GHA to auto-merge Dependabot PRs to test branch
Created new GHA workflow that creates a new testing branch with all of the open PRs from Dependabot, then notifies the team in Slack.
To make it easier to manage incoming Dependabot PRs by automatically creating test branches and notifying the team
Manually run the GHA and check the test branch it creates for all of the open Dependabot PRs.
=> [SDK-2032] Create Github Action to merge dependabot PRs

ChangeLog.md, branchreactnativetestbed/package.json, ios/RNBranch.h, package.json, react-native-branch.podspec
SDK-2140 -- Release 6.0.0
This PR upgrades the Branch iOS SDK from v2.2.0 to v3.0.0 and raises the minimum iOS version to 12.0. 
To keep React Native up to date with the native iOS SDK.
Run the testbed or integrate the `6.0.0-alpha.2` package into a react native app.
=> [SDK-2140] Update iOS SDK to v3.0.0 and raise minimum to iOS 12.0

android/src/main/java/io/branch/rnbranch/RNBranchModule.java, ios/RNBranch.m, src/index.d.ts, src/index.js
SDK-2199 -- Expose snap partner parameters API
Exposed the `addSnapPartnerParam` JS method from the native SDKs.
We added this method to our iOS and Android SDKs but haven't exposed it in the JS layer yet, so clients haven't been able to use it.
Run a test app and try to use the method to set the Snap partner parameter. Check that it is properly set, included in requests, and cleared by `clearPartnerParams()`.
=> [SDK-2199] Added addSnapPartnerParam()

ChangeLog.md, branchreactnativetestbed/package.json, package.json
2024-02-29 Version 6.1.0
- Update Android SDK to 5.9.0
- Update iOS SDK 3.2.0
- Added addSnapPartnerParameter() to support setting Snapchat partner parameters
- Added setDMAParamsForEEA() to support DMA compliance
- Removed deprecated setDebug() method
=> Release 6.1.0

ChangeLog.md, android/build.gradle, package.json, react-native-branch.podspec
SDK-2345 -- Updated native SDK versions to support setting apiURL in branch.json
Updated the iOS and Android SDK versions to the latest. Also updated the plugin version and changelog.md.
With these versions, React Native users will be able to change the Branch API base URL via the branch.json files.
Add "apiUrl": "https://api.branch.io" to the Android and iOS branch.json files in a test app. Observe that all of the Branch requests now use this URL.
=> [SDK-2345] Updated native SDK versions to support setting apiURL in branch.json

ChangeLog.md, package.json, react-native-branch.podspec
SDK-2352 update to iOS SDK 3.4.1
This update fixes an issue with deeplinks getting lost on iOS when the App is closed and `deferInitForPluginRuntime` is enabled
=> Update to iOS 3.4.1 and bump version

ChangeLog.md, android/build.gradle, branch-sdk-automation-testbed/ios/Podfile.lock, branch-sdk-automation-testbed/package-lock.json, branch-sdk-automation-testbed/package.json, branchreactnativetestbed/android/app/src/main/AndroidManifest.xml, branchreactnativetestbed/ios/Podfile.lock, branchreactnativetestbed/ios/branchreactnativetestbed.xcodeproj/project.pbxproj, branchreactnativetestbed/ios/branchreactnativetestbed/Info.plist, branchreactnativetestbed/ios/branchreactnativetestbed/branchreactnativetestbed.entitlements, branchreactnativetestbed/package-lock.json, branchreactnativetestbed/package.json, package-lock.json, package.json, react-native-branch.podspec
SDK-2456 -- Bump native SDK versions
Updated the Branch Android SDK to 5.12.1 and iOS to 3.4.4. Also updated the changelog and the plugin version to 6.2.2.
To provide clients with access to the latest features from our native SDKs.
Ensure the latest version works with the version bumps. Integrate the alpha package into a test app, version `6.2.2-alpha.0`
=> [SDK-2456] Updated Branch SDK versions and prepare v6.2.2 release

.gitignore, ChangeLog.md, branch-sdk-automation-testbed/package.json, branchreactnativetestbed/android/settings.gradle, branchreactnativetestbed/ios/Podfile.lock, branchreactnativetestbed/package-lock.json, branchreactnativetestbed/package.json, package.json, react-native-branch.podspec
=> Release 6.4.0

ChangeLog.md, android/build.gradle, package.json
2025-05-28 Version 6.7.1
- Update Android SDK to 5.18.1
=> Release 6.7.1
