BranchMetrics/react-native-branch-deep-linking-attribution

- README.md
- RNBranch/RNBranch.m
- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- docs/installation.md
- package.json
- src/branchUniversalObject.js
- src/index.js
- test/index.js
While these features are not complete nor fully tested, I think it best to get this merged into master on the sooner side so we can get more eyes on this and speed up development
> Subscribe Handles non-Branch links, Universal Object Support, other cleanup

- react-native-branch.podspec
Changes to podspec:
1. Added 'React' as dependency
2. The values in podspec are populated from package.json
> Fixed podspec, added dependency to React, so it can be properly linked

- package.json
> [deps] update react-native-mock

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- ios/RNBranch.m
- src/index.js
- test/helpers/RNBranch.mock.js
- do not double emit session event
- clear session results upon redemptions, as to avoid duplicate redemption
> Improve support for non-branch deep linking

- android/build.gradle
- ios/RNBranch.h
- ios/RNBranch.m
> Android sdk 2

- testbed/README.md
- testbed/testbed_carthage/android/app/app.iml
- testbed/testbed_carthage/android/app/build.gradle
- testbed/testbed_carthage/android/app/src/main/AndroidManifest.xml
- testbed/testbed_carthage/android/app/src/main/java/com/testbed_carthage/MainActivity.java
- testbed/testbed_carthage/android/app/src/main/java/com/testbed_carthage/MainApplication.java
- testbed/testbed_carthage/android/build.gradle
- testbed/testbed_carthage/android/gradle/wrapper/gradle-wrapper.properties
- testbed/testbed_carthage/android/settings.gradle
- testbed/testbed_carthage/android/testbed_carthage.iml
Added basic Android Branch integration to testbed_carthage.
> Android for testbed_carthage

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- ios/BranchUniversalObject+RNBranch.m
This adds support for the remaining properties of the BUO:
- automaticallyListOnSpotlight (iOS)
- currency
- expirationDate
- keywords
- (content) type
> More properties 0.9

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- ios/BranchLinkProperties+RNBranch.h
- ios/BranchLinkProperties+RNBranch.m
- ios/BranchUniversalObject+RNBranch.h
- ios/BranchUniversalObject+RNBranch.m
- ios/NSObject+RNBranch.h
- ios/NSObject+RNBranch.m
- ios/RNBranch.m
- ios/RNBranch.xcodeproj/project.pbxproj
- ios/RNBranchProperty.h
- ios/RNBranchProperty.m
- react-native-branch.podspec
- src/index.js
- testbed/testbed_carthage/android/app/app.iml
- testbed/testbed_cocoapods/android/app/app.iml
Include changes from 0.9.1 in preparation for a 1.0.1 release.
> Updates from 0.9.1

- ChangeLog.md
- docs/installation.md
- Added a ChangeLog
- Carthage was only mentioned in the README, not the full install instructions
> ChangeLog and Carthage in full install instructions

- testbed/testbed_carthage/ios/testbed_carthage.xcodeproj/project.pbxproj
- testbed/testbed_carthage/ios/testbed_carthage.xcodeproj/xcshareddata/xcschemes/testbed_carthage.xcscheme
Disable the verbose OS-level logging in the Xcode console for testbed_carthage.
> Added an OS_ACTIVITY_MODE to quiet testbed_carthage

- package.json
- react-native-branch.podspec
In package.json:
- Updated version number
- Corrected repo URL
In react-native-branch.podspec:
- Corrected license, homepage and source fields parsed from package.json
- Updated Branch SDK dependency requirement
> Corrected some issues in the podspec and package.json

- src/branchUniversalObject.js
I was mainly testing the failure case before. The `then` clause was firing if the `catch` clause did not, causing an error. This is the correct logic. Both cases work now.
> Restructured promise handling

- README.md
- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- ios/RNBranch.m
- src/branchUniversalObject.js
- src/index.js
- testbed/testbed_carthage/src/BranchMethods.js
- testbed/testbed_cocoapods/android/app/app.iml
- testbed/testbed_cocoapods/src/BranchMethods.js
Added support for calling userCompletedAction on a BUO, e.g.:
```js
import branch, { RegisterViewEvent } from 'react-native-branch'
let universalObject = branch.createBranchUniversalObject('abc', { automaticallyListOnSpotlight: true })
universalObject.userCompletedAction(RegisterViewEvent)
```
> BUO.userCompletedAction and event constants

- README.md
- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- ios/BranchUniversalObject+RNBranch.h
- ios/BranchUniversalObject+RNBranch.m
- ios/RNBranch.m
- src/branchUniversalObject.js
- testbed/testbed_cocoapods/android/app/app.iml
The Android SDK supports this, but iOS currently doesn't. This provides a workaround until and unless the native iOS SDK supports `[BranchUniversalObject userCompletedAction:withState:]`.
> Support for custom params in BUO.userCompletedAction

- README.md
- package.json
- testbed/testbed_carthage/src/BranchMethods.js
- testbed/testbed_cocoapods/src/BranchMethods.js
- Document the `release` and `userCompletedAction` methods.
- Add `this.buo.release()` to `componentWillUnmount()` in testbed apps.
- Update version to 1.1.0.
> Doc updates

- README.md
Indicate that `createBranchUniversalObject` is now async.
> 1.1 doc update

- README.md
- docs/Release-2.0.0.md
- package.json
- testbed/README.md
- testbed/testbed_native_ios/README.md
- testbed/testbed_simple/README.md
- Mention 2.0.0 in README
- Added Release-2.0.0.md outlining what's present in 2.0.0
- Added/updated READMEs for testbed apps
- Update to version 2.0.0-beta.1
> 2.0 doc updates

- ios/BranchUniversalObject+RNBranch.m
- ios/NSObject+RNBranch.m
- ios/RNBranch.m
- ios/RNBranchAgingDictionary.h
- ios/RNBranchAgingDictionary.m
- ios/RNBranchAgingItem.h
- ios/RNBranchAgingItem.m
- ios/RNBranchProperty.h
- ios/RNBranchProperty.m
These are all straightforward changes recommended by Xcode.
> Clean up Xcode warnings.

- examples/testbed_native_ios/Podfile.lock
- ios/Branch-SDK.podspec
- ios/Branch-SDK/Branch-SDK/BNCCommerceEvent.m
- ios/Branch-SDK/Branch-SDK/BNCConfig.m
- ios/Branch-SDK/Branch-SDK/BNCDebug.h
- ios/Branch-SDK/Branch-SDK/BNCDebug.m
- ios/Branch-SDK/Branch-SDK/BNCFabricAnswers.m
- ios/Branch-SDK/Branch-SDK/BNCLog.h
- ios/Branch-SDK/Branch-SDK/BNCLog.m
- ios/Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
- ios/Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
- ios/Branch-SDK/Branch-SDK/BNCSystemObserver.h
- ios/Branch-SDK/Branch-SDK/BNCSystemObserver.m
- ios/Branch-SDK/Branch-SDK/BNCXcode7Support.h
- ios/Branch-SDK/Branch-SDK/Branch.h
- ios/Branch-SDK/Branch-SDK/Branch.m
- ios/Branch-SDK/Branch-SDK/BranchActivityItemProvider.h
- ios/Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
- ios/Branch-SDK/Branch-SDK/BranchShareLink.h
- ios/Branch-SDK/Branch-SDK/BranchShareLink.m
- ios/Branch-SDK/Branch-SDK/BranchUniversalObject.h
- ios/Branch-SDK/Branch-SDK/BranchUniversalObject.m
- ios/Branch-SDK/Branch-SDK/NSString+Branch.h
- ios/Branch-SDK/Branch-SDK/NSString+Branch.m
- ios/Branch-SDK/Branch-SDK/Requests/BranchLoadRewardsRequest.m
- ios/Branch-SDK/Branch-SDK/Requests/BranchShortUrlRequest.m
- ios/Branch-SDK/Branch-SDK/Requests/BranchShortUrlSyncRequest.m
- ios/RNBranch.xcodeproj/project.pbxproj
This includes a pod update to testbed_native_ios, which uses the Branch-SDK pod in the NPM module.
> Update included iOS SDK to 0.14.9

- examples/webview_example/android/app/src/main/AndroidManifest.xml
The MainActivity in webview_example was missing android:launchMode="singleTask"
> Add singleTask to MainActivity in webview_example

- src/index.js
This worked well in testing with delays to simulate loading a large RN app.
> #79: Attempt to address initialization race

- ios/RNBranch.h
- ios/RNBranch.m
This makes notification handling more convenient.
> Added BranchUniversalObject and BranchLinkProperties to notification

- examples/testbed_native_ios/Podfile.lock
- examples/testbed_native_ios/testbed_native_ios.xcodeproj/project.pbxproj
- examples/testbed_native_ios/testbed_native_ios/testbed_native_ios.entitlements
Also updated the bundle identifier, team and associated domains to match the branch_key.
> Remove empty main.jsbundle from testbed_native_ios project

- examples/testbed_native_ios/testbed_native_ios.xcodeproj/project.pbxproj
- examples/testbed_native_ios/testbed_native_ios.xcodeproj/xcshareddata/xcschemes/testbed_native_ios-Test.xcscheme
- examples/testbed_native_ios/testbed_native_ios/AppDelegate.m
This provides an Objective-C example where webview_example_native_ios provides a Swift example.
> Added Test configurations and scheme to testbed_native_ios

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
Hello,
I wanted to create a link with alias, unfortunelty this didn't worked. After a bit of research, its look like params : **alias**, **campaign**, **stage** were not properly modified via **setAlias**, **setCampaign**, **setStage** accordinaly in [createLinkProperties](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/android/src/main/java/io/branch/rnbranch/RNBranchModule.java#L321)
Version of Branch sdk : 0.14.12
Version of RN Branch : 1.1.1
> Fix Android createLinkProperties

- CONTRIBUTING.md
- runAllTests
This is useful for contributors and other devs.
> Added runAllTests script

- src/index.js
- test/index.js
> [OS-37] Initialization race

- .travis.yml
- test/helpers/RNBranch.mock.js
- test/index.js
This simplifies a couple of tests considerably.
> Added a simple JS mocking mechanism

- docs/setup.md
> Add initialization instructions for Swift

- README.md
- docs/setup.md
This is the first draft. It is current and accurate, but still needs some work.
> Docs rewrite

- README.md
- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- examples/testbed_native_android/src/BranchMethods.js
- examples/testbed_native_ios/src/BranchMethods.js
- examples/testbed_simple/src/BranchMethods.js
- ios/RNBranch.m
- src/index.js
Fix #249.
Added the `sendCommerceEvent` method, including documentation in the README and examples of use in the testbed apps.
> Add sendCommerceEvent method

- Gemfile.lock
- fastlane/lib/update_native_sdks.rb
Use the `patch` action instead of the deprecated `apply_patch`
> Update to SDK automation

- README.md
- examples/testbed_native_android/android/app/proguard-rules.pro
- examples/testbed_simple/android/app/proguard-rules.pro
- examples/webview_example/android/app/proguard-rules.pro
This addresses #225, #255, #256.
> Proguard patch

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- ios/BranchEvent+RNBranch.m
- ios/RNBranch.m
- src/BranchEvent.js
- src/branchUniversalObject.js
- Exported BranchEvent constants from Android to JS as RNBranch.STANDARD_EVENT_ADD_TO_CART, etc.
- Implemented RNBranch.logEvent() method for Android.
- Some improvements to JS and iOS.
> V2 events: Android

- ios/BranchContentMetadata+RNBranch.m
- ios/RNBranch.m
- src/branchUniversalObject.js
Corrected the selector used for ratingAverage.
Ensure that `userCompletedAction(RegisterViewEvent)` generates a `BranchEvent.ViewItem` (v2) event.
> Field mapping

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- Efficiently detects whether standard event or custom event and uses BranchEvent to build corresponding event instance.
> Fixes the issue in creating custom branch event.

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
Fixing issue : Integer values are read as double by default.
> Issue 314 int control param android causes invalid opg property

- README.md
Updated the documentation. Added super call inside onNewIntent.
> Issue 357 super call on new intent

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- examples/webview_example/android/app/src/main/AndroidManifest.xml
- examples/webview_example/android/app/src/main/java/com/webview_example/MainApplication.java
- examples/webview_example/android/build.gradle
- examples/webview_example/branch.debug.json
- examples/webview_example/branch.json
This is a wrapper method that allows us to call `Branch.getAutoInstance()` with the appropriate key from branch.json. This also lays the groundwork for deferring `Branch.getAutoInstance()` until JS has loaded in order to support setting keys from JS.
> RNBranchModule.getAutoInstance()

- fastlane/lib/actions/update_native_sdks.rb
Update version of Android from Maven instead of jara when using native_update lane.
> Automation updates for 3.x

- README.md
- docs/carthage.md
- docs/cocoapods.md
- docs/convert-to-react-pod.md
These changes detail two ways to integrate using CocoaPods as well as Carthage.
> Docs for all native SDK installation options

- examples/browser_example/android/app/build.gradle
- examples/testbed_native_android/.babelrc
- examples/testbed_native_android/android/app/build.gradle
- examples/testbed_native_android/android/app/src/debug/AndroidManifest.xml
- examples/testbed_native_android/android/app/src/main/AndroidManifest.xml
- examples/testbed_native_android/android/app/src/main/java/io/branch/testbed_native_android/MainActivity.java
- examples/testbed_native_android/android/app/src/main/java/io/branch/testbed_native_android/MainApplication.java
- examples/testbed_native_android/android/app/src/main/res/layout/activity_main.xml
- examples/testbed_native_android/android/app/src/main/res/layout/content_main.xml
- examples/testbed_native_android/android/build.gradle
- examples/testbed_native_android/android/gradle/wrapper/gradle-wrapper.properties
- examples/testbed_native_android/android/settings.gradle
- examples/testbed_native_android/babel.config.js
- examples/testbed_native_android/package.json
- examples/testbed_native_android/yarn.lock
- examples/testbed_simple/android/app/build.gradle
- examples/webview_example/android/app/build.gradle
- examples/webview_tutorial/android/app/build.gradle
Also fixed an issue in the app/build.gradle for each pure RN example that didn't surface during testing.
> Update testbed_native_android to RN 0.60.3

- examples/testbed_simple/ios/Podfile.lock
- ios/RNBranch.h
- ios/RNBranch.m
- react-native-branch.podspec
0.28.1 includes changes to remove UIWebView and replace with WebKit to comply with Apple's guidelines.
> Update to Native iOS SDK 0.28.1

- android/build.gradle
- react-native-branch.podspec
This only updates the binaries so previous functionality works.  It does not expose the new query methods.
> SDK-509 update for iOS 0.29.0 and android 4.1.0

- ChangeLog.md
- android/build.gradle
- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- examples/testbed_simple/ios/Podfile.lock
- ios/RNBranch.h
- ios/RNBranch.m
- package.json
- react-native-branch.podspec
Update to iOS 0.29.0
Update to Android 4.1.0
> SDK-509 update react native

- ios/RNBranch.m
Without this fix, it's not possible to use this library.
> Fix minimum native iOS SDK requirement

- .travis.yml
- android/build.gradle
- ios/RNBranch.m
- react-native-branch.podspec
Remove version check, allow automatic patch updates
> SDK-576 update react native

- ios/RNBranch.m
> SDK-854 only call back on successful completion.  ignore cancel

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
This is copied and pasted from the master branch (4.x).
> [INTENG-9296] Import crash solution from master branch.

- native-tests/ios/Podfile.lock
- react-native-branch.podspec
Use `./runAllTests` to check unit tests. Did some basic testing in the examples in a different branch as well.
> Update native iOS SDK to 0.35.0.

- android/build.gradle
- native-tests/ios/Podfile.lock
- package-lock.json
- react-native-branch.podspec
- yarn.lock
Tested using `./runAllTests` and by updating webview_example to use the local repo.
> Update native Branch SDKs to Android 5.0.4, iOS 0.36.0

- package.json
- src/index.d.ts
Been using some in-house typescript definitions for a while now -- figured I'd clean them up and share here since issue #523 has been around for a while, and #224 never landed.
For making these, I took some liberties:
- Deprecated and private methods have **been omitted**.
- Undocumented exports have **been omitted** (`BranchSubscription` and the `Branch` class constructor)
- I did not see these documented anywhere, so I did not include the exports, even though they are present in the JS.
- A few new types **ARE exported** for convenience
- `BranchParams` (returned from `getLatestReferringParams` and present on subscription `event.params`)
- `BranchSubscriptionEvent` (`{ params, error, uri }` in subscribe callback)
- `BranchOpenStartEvent` (`{ uri, cachedInitialEvent }` in openStart …
> feat: add TypeScript definition

- ChangeLog.md
- android/build.gradle
- package.json
> CORE-2325 prep release

- react-native-branch.podspec
Added support for Swift, I need this modified to use `react-native-branch` in the config plugin.
See https://github.com/expo/config-plugins/pull/28
cc: @Kudo from the Expo team
> chore: support for Swift

- ChangeLog.md
- package.json
- Null checks for listeners. Thanks ilyagru!
- Depend on React-Core instead of React. Thanks radko93!
- Use @ReactModule annotation. Thanks janicduplessis!
> Bump version for more community PRs

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- examples/testbed_simple/src/BranchMethods.js
- src/index.d.ts
- src/index.js
Added react methods to set the pre install campaign and pre install adPartner.
https://branch.atlassian.net/browse/SDK-1513
> Expose setPreinstallCampaign and setPreinstallPartner

- ChangeLog.md
- package.json
SDK-1501 - [React Native] Release 5.5.0
2022-07-20 Version 5.5.0
- Branch QR code creation support added.
```js
getBranchQRCode: (
settings: BranchQRCodeSettings,
branchUniversalObject: BranchUniversalObjectOptions,
linkProperties: BranchLinkProperties,
controlParams: BranchLinkControlParams, 
) => Promise<string>;
- Support for preinstall analytics.
```js
setPreInstallCampaign = (campaign) => RNBranch.setPreinstallCampaign(campaign)
setPreInstallPartner = (partner) => RNBranch.setPreinstallPartner(partner)
```
- Update react-native to 0.63.0
- Update Android SDK to 5.2.0
- Update iOS SDK to 1.43.1
> Release 5.5.0

- ChangeLog.md
- android/build.gradle
- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- package.json
- react-native-branch.podspec
SDK-1620 - [React Native] Release 5.6.0
2022-09-30 Version 5.6.0
- Update Android SDK to 5.2.4
- Update iOS SDK to 1.43.2
- Fix BranchUniversalObject showShareSheet return type definition (thanks romanlitvin)
- Change customData type definition to String String dictionary (thanks vincent-paing!)
- Fixed clearPartnerParameters call (thanks danilobuerger!)
- Add callback to setIdentity in new function `setIdentityAsync`
> Release 5.6.0

- ChangeLog.md
- android/build.gradle
- package.json
Update to include `Branch.setIsUserAgentSync(true)`
> Update Android SDK to 5.2.5

- src/index.d.ts
No Issue
Export types so they can be exported via Branch package
- Developer Experience
Linked locally
> fix: Export types exposed via methods

- .github/workflows/automation-trigger-test.yml
For ReactNative CI/ CD implementation
> automation-trigger-test.yml

- android/build.gradle
- package.json
- react-native-branch.podspec
SDK-1697
Update dependencies.
iOS to 1.45.2
Android to 5.2.7
Update native SDK versions. Note this increases the min iOS version to iOS 11.
Should see the correct native SDK versions in logs.
> Sdk 1697 update native sdk versions

- .github/dependabot.yml
SDK-1745 -- Add Dependabot
Add Dependabot to this repo to check and automate dependencies for :
- npm packages
- Github Actions
> SDK-1745 : Create dependabot.yml

- .github/workflows/gate-keeper.yml
- .github/workflows/gate-keepr.yml
- package.json
- test/BranchSubscriber.test.js
- test/RNBranchMock.js
SDK-1792
- Adds codecoverage reporting tool codecov as part of GHA
- Fix unit test failures by mocking notifyNativeToInit
- Run tests with --coverage
> SDK-1792: Integrate codecov

- ChangeLog.md
- branchreactnativetestbed/package.json
- package.json
SDK-1862 -- Release 5.9.0
This PR updates the version from 5.8.0 to 5.9.0, updated the changelog.md, and updated the testbed to use the latest public SDK version.
Prepare for release.
Check to see that the changelog is accurate and the version has been updated to the correct number.
> [SDK-1862] Release 5.9.0

- .github/workflows/gate-keeper.yml
- updates the target branch from main to master
- removes codecov token as its not needed for public repos
> ci(gha) : Update branch name in  gate-keeper.yml

- android/src/main/java/io/branch/rnbranch/RNBranchModule.java
- branchreactnativetestbed/App.tsx
- branchreactnativetestbed/components/BranchWrapper.ts
- ios/RNBranch.m
- src/branchUniversalObject.js
- src/index.js
SDK-2057 -- Removed v1/event code
Removed `userCompletedAction` and `sendCommerceEvent` code from `RNBranchModule.java`, `RNBranch.m`, `branchUniversalObject.js`, and `index.js`.
Remove old code that has been deprecated for a sufficient amount of time.
Integrate the SDK, run the app, and run the tests to ensure everything is still functioning correctly.
> [SDK-2057] Removed v1/event code

- android/build.gradle
- react-native-branch.podspec
SDK-2135 -- Bump iOS and Android versions
Updated the Branch Android SDK from 5.5.0 -> 5.7.0 and the Branch iOS SDK from 2.2.0 -> 2.2.1
To keep the SDK up to date and include fixes in the recent Android releases.
Test the updated version in a sample app.
> [SDK-2135] Update native SDK versions

- ChangeLog.md
- branchreactnativetestbed/package.json
- package.json
SDK-2163 -- Release 5.9.1
This PR updates the version from 5.9.0 to 5.9.1, updated the changelog.md, and updated the testbed to use the latest public SDK version.
Prepare for release.
Check to see that the changelog is accurate and the version has been updated to the correct number.
> [SDK2163] Release 5.9.1

- ChangeLog.md
- android/build.gradle
- branch-sdk-automation-testbed/package.json
- branchreactnativetestbed/package.json
- package.json
- Update Android SDK to 5.7.1 to include important bug fix.
> Release 5.9.2

- .github/workflows/gate-keeper.yml
> run gate-keeper.yml against master to upload coverage reports

- .github/workflows/gate-keeper.yml
Reverts BranchMetrics/react-native-branch-deep-linking-attribution#948
> Revert "Update gate-keeper.yml"

- .github/workflows/gate-keeper.yml
> Update gate-keeper.yml to run on any commit

- ChangeLog.md
- android/build.gradle
- package.json
- react-native-branch.podspec
- Update iOS SDK to 3.10.0
- Update Android SDK to 5.16.1
> Release 6.6.0
